### PR TITLE
Usability Upgrades - Fast Publishing and File Watching

### PR DESCRIPTION
**Pull request by freeformflow**
1. Made render a p9k procedure
2. Implemented Lamba-only Sky update that can be invoked with `sky update <env>`  It will publish the lambda only of whatever is in the code archive. 
3. Implemented alpha version of file watcher to speed build.  Invoked with `sky watch`.  It will watch your `src/` and `node_module` directories and update the package.zip used to hold your Lambdas in the Cloud.

### CODE REVIEW

**Comment by automatthew** [comment]
Why should any of these be p9k procedures?  I found it very difficult to trace what was happening in panda-sky, which is why I specifically made the `render` command use a simple, easy-to-find function.

What am I missing?

**Comment by automatthew** [comment]
Also, shouldn't this be 3 different PRs, one per major change?

**Comment by freeformflow** [comment]
@dyoder, I agree with Matthew that the p9k routines can be a little awkward to use sometimes.  I know that you bulilt the first ones to do filesystem tasks with Haiku, like the asset pipeline transcompilation of CoffeeScript to JS.  Does it make sense to continue using p9k in Panda Sky, however?

**Comment by freeformflow** [comment]
@automatthew, I won't be able to get to it until tonight, but would you like me to split this into three PRs?

**Comment by freeformflow** [comment]
This is subsumed by PRs #77 #78 and #79.  Closing.

**Pull request closed without merging**
